FROM ubuntu:18.04

# Update release
RUN apt-get update
RUN apt-get upgrade -y

# Copy the configuration
#COPY nginx.conf /etc/nginx/nginx.conf

# Copy the 
#WORKDIR /usr/share/nginx/html
#COPY dist/camera-app/ .
